quarkus:

  smallrye-metrics:
    path: '/metrics'
    extensions:
      enabled: true
    micrometer:
      compatibility: false
    jaxrs:
      enabled: false

  health:
    extensions:
      enabled: true
    openapi:
      included: true

  smallrye-health:
    root-path: '/health'
    liveness-path: '/live'
    readiness-path: '/ready'
    wellness-path: '/well'
    group-path: '/group'
    ui:
      root-path: '/health-ui'
      always-include: true
      enable: true

  smallrye-openapi:
    path: '/openapi'

  swagger-ui:
    always-include: true
    path: '/swagger-ui'

  log:
    level: INFO
    console:
      color: true