quarkus:

  package:
    # type: uber-jar
    type: fast-jar

  datasource:
    db-kind: 'h2'
    jdbc:
      url: 'jdbc:h2:tcp://localhost/mem:world;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
    health:
      enabled: true
    metrics:
      enabled: true

  hibernate-orm:
    database:
      generation: drop-and-create

  flyway:
    #migrate-at-start: true
    migrate-at-start: false
    locations: 'db/migration'
    connect-retries: 1
    table: 'flyway_history'


  smallrye-metrics:
    path: '/metrics'
    extensions:
      enabled: true
    micrometer:
      compatibility: false
    jaxrs:
      enabled: true

  health:
    extensions:
      enabled: true
    openapi:
      included: true

  smallrye-health:
    root-path: '/health'
    liveness-path: '/live'
    readiness-path: '/ready'
    wellness-path: '/well'
    group-path: '/group'
    ui:
      root-path: '/health-ui'
      always-include: true
      enable: true

  jaeger:
    enabled: true
    metrics:
      enabled: true
    endpoint: "http://localhost14268/api/traces"
    service-name: code-with-quarkus
    sampler-type: const
    sampler-param: 1

  smallrye-openapi:
    path: '/openapi'

  swagger-ui:
    always-include: true
    path: '/swagger-ui'

  log:
    level: 'INFO'
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{1.}] (%t) %s%e%n"
      color: true
    category:
      "info.maila":
        level: TRACE
      "io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor":
        level: ERROR

"%prod":
  quarkus:
    smallrye-health:
      ui:
        enable: false